version: "2"
services:
  
  loyalty:
    build: .
    container_name: "loyalty"
    depends_on:
      - mongo
    ports:
      - "8080:8080"

  mongo:
    image: mongo:3.6
    container_name: "mongo"
    ports:
      - "27017:27017"
    environment:
      AUTH: 'no'
    command: --smallfiles
