version: '2'
services:
  
  loyalty:
    build: .
    depends_on:
      - mongo
    links:
      - mongo
    ports:
      - "8080:8080"
    environment:
      MONGODB_URL=mongodb://mongo:27017

  mongo:
    image: mongo:3.6
    ports:
      - "27017:27017"
    environment:
      AUTH: 'no'
    command: --smallfiles
